---

- name: Add any needed apt keys
  apt_key:
    url="{{ item }}"
    state=present
  with_items: '{{ hpkeys }}'

- name: Set up apt repos usually set up in cobbler
  apt_repository:
    repo={{ item }}
    state=present
    update_cache=no
  with_items: '{{ repos.trusty }}'
  when: ansible_distribution_release == 'trusty'

- name: Set up apt repos usually set up in cobbler
  apt_repository:
    repo={{ item }}
    state=present
    update_cache=no
  with_items: '{{ repos.xenial }}'
  when: ansible_distribution_release == 'xenial'

- name: Refresh apt cache
  apt:
    update_cache: yes
